# Generated by Django 3.2 on 2022-07-27 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Revendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('cpf', models.BigIntegerField(unique=True)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('nm_completo', models.CharField(max_length=250, null=True)),
                ('email', models.CharField(max_length=60, null=True)),
            ],
            options={
                'db_table': 'revendedor',
            },
        ),
    ]
