# Generated by Django 3.2 on 2022-07-28 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraRevendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('data', models.DateField()),
                ('status', models.CharField(choices=[('aprovado', 'Aprovado'), ('em_validacao', 'Em validação')], default='em_validacao', max_length=30)),
                ('perc_cashback', models.DecimalField(decimal_places=2, max_digits=7)),
                ('vlr_cashback', models.CharField(choices=[('aprovado', 'Aprovado'), ('em_validacao', 'Em validação')], default='em_validacao', max_length=30)),
                ('revendedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compra_revendedor',
            },
        ),
    ]
