# Generated by Django 3.2 on 2022-07-28 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficio', '0002_comprarevendedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprarevendedor',
            name='perc_cashback',
        ),
        migrations.RemoveField(
            model_name='comprarevendedor',
            name='vlr_cashback',
        ),
    ]
