# Generated by Django 3.2 on 2022-07-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficio', '0003_auto_20220728_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprarevendedor',
            name='referencia',
            field=models.IntegerField(null=True),
        ),
    ]
